### ISSUE TITLE
Typescript Vue-meta type assertion don't works

### ISSUE THREAD

**Issue by karlos1337** [universal-vue/uvue#5]
**Describe the bug**
Typescript warnings using component meta tags
```ts
Argument of type '{ head: { titleTemplate(title: string): string; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, and 'head' does not exist in type 'VueClass<Vue>'.
     7 | 
     8 | @Component({
  >  9 |   head: {
```

**To Reproduce**
Fresh vue-cli project with TS, install uvue and vue-meta, try to set a component meta tag

**Expected behavior**
Type assertion for Component decorator meta keys as in vueneue (https://vueneue.github.io/docs/guide/cli-plugins.html#typescript)

**Additional context**

Please indicate versions of:
```
node: 11.2.0
vue-cli: 3.1.3
uvue: 0.1.0-aplha
os: Antergos (Arch Linux)
browser: N/A
```

**Comment by chymz** [comment]
Hi,

Thanks for reporting !

Instead of VueNeue, UVue let developers to install and configure Vue meta. So I cannot write this TypeScript definition in core package. You have to do it manually:

In your  `src/shims-vue.d.ts`, you can copy this:
https://github.com/vueneue/vueneue/blob/master/packages/%40vueneue/ssr-core/index.d.ts#L5-L20

Anyway I need to add this to documentation :smile:

**Comment by karlos1337** [comment]
Ok, I'll do as that, thanks :).
Should I close the issue or would you rather to stay here to remind you that it's still need to be documented?

Great job btw, I was hoping for something like uvue.

**Comment by chymz** [comment]
I'm keeping this open for documentation.

I'm glad you like it!
Don't be afraid to give a :star: ;)
