### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by StringKe** [universal-vue/uvue#54]
Hi, Just wandering if there are any plans to upgrade to Vue 3?

**Comment by yabab-dev** [comment]
Hi @StringKe!

Indeed, a couple months ago, I started working on a full rewrite of this plugin to be compatible with Vue 3. Everything is working great so far and performances a really good compared to Vue 2!

But I put this work on pause to wait for a more stable version of the Vue core...

Since a few days, I started working on it again and I obtained interesting results. Maybe I'll release a preview version next month!

**Comment by StringKe** [comment]
> Hi @StringKe!
> 
> Indeed, a couple months ago, I started working on a full rewrite of this plugin to be compatible with Vue 3. Everything is working great so far and performances a really good compared to Vue 2!
> 
> But I put this work on pause to wait for a more stable version of the Vue core...
> 
> Since a few days, I started working on it again and I obtained interesting results. Maybe I'll release a preview version next month!

ok, thank you for your contribution

**Comment by Raiondesu** [comment]
Hi everyone, how's this going?
Vue 3 has been released into the wild some time ago, so there's really no reason to postpone this anymore.

**Comment by yabab-dev** [comment]
Like I said in my previous comment, I'm working on It!
Actually, I've deployed a demo: https://und.ici.sh/ which use Vue 3 and next version of UVue

Sources & docs will come later

**Comment by yabab-dev** [comment]
[Closing, see this issue](https://github.com/universal-vue/uvue/issues/57)
